#!/bin/zsh

workdir=~/.dapp/testnet/2000

rm -rf chain_data && mkdir chain_data && cd chain_data

touch ./password

geth --ipcpath ${workdir}/geth.ipc \
  --datadir ${workdir} \
  account new --password ./password \
  | sed 's/^.*{\([0-9a-fA-F]\{40\}\)}.*$/0x\1/' > account1
geth --ipcpath ${workdir}/geth.ipc \
  --datadir ${workdir} \
  account new --password ./password \
  | sed 's/^.*{\([0-9a-fA-F]\{40\}\)}.*$/0x\1/' > account2
geth --ipcpath ${workdir}/geth.ipc \
  --datadir ${workdir} \
  account new --password ./password \
  | sed 's/^.*{\([0-9a-fA-F]\{40\}\)}.*$/0x\1/' > account3

node ../alloc.js
